### ISSUE TITLE
Microstepping

### ISSUE THREAD

**Issue by boromyr** [teemuatlut/TMC2208Stepper#28]
Hi, i'm using your library to drive a TMC2208 via Arduino one, but i can't use the microstepping at 256 steps, even if I set the function to driver.microsteps (256), i tried to use the other functions that deal with microstepping but nothing, I reach a maximum of 1/16.
Arduino Uno, TMC2208 v2.1, Nema17, MS1 and MS2 tested at 0-0, and 1-1, example code, adding the DIR pin, without the stepper it did not work.
I am a beginner on the subject, surely I am making a mistake from inexperience, which I cannot see.
Thank you

**Comment by teemuatlut** [comment]
Reading 256 can mean that the returned value was 0, as that means 256.
Make sure you've configured the driver to use UART comms and that the driver should use registers for microstepping value instead of the ms pins.
