### ISSUE TITLE
mystake or misunderstanding of code description in configuration_adv.h for tmc2208

### ISSUE THREAD

**Issue by mathmac** [teemuatlut/TMC2208Stepper#3]
first of all, thank you for your work on steppers

that's said, in marlin configuration_adv.h section for tmc2208 it is said : 
```
Enable this for SilentStepStick Trinamic TMC2208 UART-configurable stepper drivers.
 * Connect #_SERIAL_TX_PIN to the driver side PDN_UART pin.
 * To use the reading capabilities, also connect #_SERIAL_RX_PIN
 * to #_SERIAL_TX_PIN with a 1K resistor.
 * The drivers can also be used with hardware serial.
```

but when I'm looking at photos posted by you 
https://user-images.githubusercontent.com/7762686/30186160-06e52846-942d-11e7-9b04-1d9cfc1e1738.jpg
or on scheme by waterott https://github.com/watterott/SilentStepStick/raw/master/docs/ScriptCommunicator/hw_connection.png

it seems to be the contrary : PND_UART directly on RX (for X RX is pin 63 on ramps 1.4)
and PND_UART to 1kohm to TX (for X TX is pin 59 on ramps 1.4)

i don't know if it's a misunderstanding of TX/RX which are inverted as we understand from the stepper of from the board...

but I tried without success to write to my steppers with one direct link to TX or RX
(I've no 1kohm resistor at the moment, but I will have soon)
to verify, i've tested to write low values with M906 to see if missing steps append
I've also tested vref with multimeter but no changes when using M906

if the writting needs a 1k resistor as I think,; it's ok but the comment in marlin should be inverted

thank you for your work on steppers

**Comment by teemuatlut** [comment]
You are absolutely correct and the paragraph needs to be fixed.
