### ISSUE TITLE
Arduino uno problem

### ISSUE THREAD

**Issue by impy101** [teemuatlut/TMC2208Stepper#32]
Hello,

I've tried wiring my TMC2208 to my arduino uno, but it doesn't seem to work. Do you by any chance have a wiring guide for an Arduino uno?

**Comment by teemuatlut** [comment]
Usually it's the driver module manufacturer that provides this information.
You can find Watterott's version here: https://learn.watterott.com/silentstepstick/configurator/
Or BTT here: https://github.com/bigtreetech/BIGTREETECH-TMC2208-V3.0/blob/master/Hardware/TMC2208connect.png

You just need to connect RX to PDN_UART and using a 1kOhm resistor TX to RX.
