### ISSUE TITLE
TMC2208_SoftwareSerial RS and multipilier switched

### ISSUE THREAD

**Issue by oakdesign** [teemuatlut/TMC2208Stepper#6]
In the example sketch TMC2208_SoftwareSerial the function call for for RMS on line 26
`driver.rms_current(500, 0.11, 0.5);`
is switched and leading to overtemperature within a few seconds
`void TMC2208Stepper::rms_current(uint16_t mA, float multiplier, float RS)`
so should be updated to 
`driver.rms_current(500, 0.5, 0.11);`

**Comment by teemuatlut** [comment]
Thanks! Merged and fixed for step interrupts example as well.
