### ISSUE TITLE
Help using library outside of marlin

### ISSUE THREAD

**Issue by Kyzuuh** [teemuatlut/TMC2208Stepper#9]
I have wired up my driver as shown in the imgur images.  My UART pin is connected to my software RX pin and a 1k resistor is jumping my RX and TX.  My driver won't change from 8 microsteps unless I physically use the MS1, MS2 pins.  I wrote the line at my setup:
driver.mstep_reg_select(1);
driver.mstep(256);

Please help!  This is frustrating me to no end and I'm unable to decode everything you've got going on in the library.

**Comment by teemuatlut** [comment]
Do the provided examples work for you?

**Comment by Kyzuuh** [comment]
Sorry, I think I'm just stupid..... lol I was using the UART pin, which is the wrong one!  Haha!  After reading through the library for a while, I must say though, this library is excellent!

**Comment by Kyzuuh** [comment]
Now I just need to figure out how to make it go faster because the microcontroller is unable to make it step fast enough to go like 2mm/s at 256uSteps
